### ISSUE TITLE
Remove overlay on dispose

### ISSUE THREAD

**Issue by glorpy** [apgapg/search_widget#10]
I have an icon that opens and closes the SearchWidget. It works great unless I close it without selecting a result. The search results list remains in the overlay even after the SearchWidget is disposed if no item was selected from within the results.

**Comment by apgapg** [comment]
Okay got the problem. Will remove overlay on dispose. Thanks for poining out the issue

**Comment by apgapg** [comment]
Fixed in v1.0.2
