### ISSUE TITLE
[web] Positioning issue with overlay

### ISSUE THREAD

**Issue by rofrankel** [apgapg/search_widget#12]
I'm new to Flutter and so wasn't able to figure out quite what's going wrong, but I can't get SearchWidget to work on web.  The Inkwell gets highlighted when my cursor is at some offset from the actual list item, and clicking when the inkwell is highlighted just closes the overlay.  Clicking on the actual list item doesn't work either.  In both cases the overlay just gets closed.

I suspect it has something to do with the Positioned or CompositedTransformFollower widgets.  [This gist](https://gist.github.com/rofrankel/c8307fcf994dddd4c3793b1ca2f92666) has a trivial example Flutter web app that demonstrates the issue.

Would love to get this working, other than this issue it seems to be a really nice widget.  Let me know how I can help debug.

**Comment by rofrankel** [comment]
Oh, this might be https://github.com/flutter/flutter/issues/50800.

**Comment by rofrankel** [comment]
Update: I tried the workaround suggested in https://github.com/danvick/flutter_chips_input/issues/20 and it resolved the highlighting issue (onHover now triggers correctly), but I still can't select items (onTap does not trigger).

**Comment by apgapg** [comment]
Yes it may be due to using on web. I will check it though

**Comment by apgapg** [comment]
In your code you defined onQueryBuilder as null. You have to provide query builder. See docs

**Comment by rofrankel** [comment]
I was just trying to keep the example minimal.  Does a null queryBuilder matter if I don't type anything into the search widget, and just try to click something in the overlay?  Seems like it wouldn't get invoked anyway in that case.  (Plus, in my real app, the queryBuilder is not null, so I don't think that's the problem.)

**Comment by apgapg** [comment]
Yes querybuilder actually returns out the filtered items list. if null may cause issues

**Comment by apgapg** [comment]
Overlay thing might be web issue. I can't really help if its too technical like composite widgets as you mentioned above

**Comment by rofrankel** [comment]
OK, thanks anyway, I guess I'll close this and keep an eye on flutter/flutter#50800.

**Comment by rofrankel** [comment]
I played with this a bit more.  It looks like maybe the listener added to _focusNode in init() is removing the overlay before the click can register?
