### ISSUE TITLE
Select value in textfield

### ISSUE THREAD

**Issue by SJente** [apgapg/search_widget#2]
Goodmorning again,

Went through your packages and this is exactly what i need. The only thing i would like to have different is that whenever you choose an item, it is selected in the textField and not in a card below the searchfield. I tried to sent the controller to the selectedItemBuilder and set the text from there, but that didn't seem to work. 

Is there any way on doing this?

**Comment by apgapg** [comment]
Hi,
Currently the text field gets erased upon selecting a value. I will add a parameter for it. Expect the release by today itself. Thanks

**Comment by MatthewRamsey** [comment]
Was this parameter added? I would like to do similar functionality? Thanks for a great widget!

**Comment by emilson-silva** [comment]
Seu Widget me ajudou muito obrigado!

**Comment by apgapg** [comment]
Yes onItemSelected is added now
