### ISSUE TITLE
Can,t access selected item 

### ISSUE THREAD

**Issue by DedSecTeam17** [apgapg/search_widget#3]
I can't access my selected item outside  "selectedItemBuilder" and even can,t set state 
setting state cause problem

**Comment by apgapg** [comment]
Thanks for opening the issue.
For the first issue, i will add an item selected callback which will be fired when an item is selected. For the second problem can you please give some code sample to better replicate it?

**Comment by DedSecTeam17** [comment]
the second problem related to the first, second problem it,s that I tried to "set state" in order to get selected item to be reflected the item that I will be used in future for any reason. so fixing the first problem will cause  fix the second

**Comment by apgapg** [comment]
Fixed in v1.0.0
