### ISSUE TITLE
The method 'markNeedsBuild' was called on null.

### ISSUE THREAD

**Issue by tula-Intelads** [apgapg/search_widget#4]
`The method 'markNeedsBuild' was called on null.
Receiver: null
Tried calling: markNeedsBuild() >>>> TRACE <<<< #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      MySingleChoiceSearchState.init.<anonymous closure> (package:search_widget/search_widget.dart:109:22)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
#4      TextEditingController.clear (package:flutter/src/widgets/editable_text.dart:183:5)
#5      MySingleChoiceSearchState.onDropDownItemTap (package:search_widget/search_widget.dart:193:17)
#6      MySingleChoiceSearchState.onTap.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:search_widget/search_widget.dart:257:39)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flu<…>`

**Comment by Michael-Peer** [comment]
Same problem here

**Comment by apgapg** [comment]
Issue will be fixed soon. Meanwhile PR is welcome

**Comment by danieramiz** [comment]
where is the fix?

**Comment by jatempa** [comment]
PR#6
