### ISSUE TITLE
Android emulator doesn't work

### ISSUE THREAD

**Issue by mohammadreza490** [apgapg/search_widget#5]
when I add this widget as dependency to my Pubspec.yaml file, the app will crash when I run it in debug mode on an android emulator and it gives me this error:

> error: a type with the same simple name is already defined by the single-type-import of KeyboardVisibilityPlugin
> import com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin;
> ^
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> > 

the version for the widget is search_widget: ^0.2.0
the app works without it

**Comment by apgapg** [comment]
Fixed in v1.0.0
