### ISSUE TITLE
After I updated the flutter v1.13.2 He is returning this error to me.

### ISSUE THREAD

**Issue by emilson-silva** [apgapg/search_widget#7]
C:\Users\Mobile02\AndroidStudioProjects\siga_atividade_coletiva\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:5: error: a type with the same simple name is already defined by the single-type-import of KeyboardVisibilityPlugin
import com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin;
^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 40s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by apgapg** [comment]
Fixed in v1.0.1
