### ISSUE TITLE
Showing Error in Both iOS and Android

### ISSUE THREAD

**Issue by balajiks-dev** [apgapg/search_widget#8]
It's returning error like this in both Android and iOS

/ .  ***/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:6: error: a type with the same simple name is already defined by the single-type-import of KeyboardVisibilityPlugin
import com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin;
^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org .   .\

**Comment by apgapg** [comment]
Fixed in v1.0.1
