### ISSUE TITLE
Exception caught by services library: MissingPluginException

### ISSUE THREAD

**Issue by anthonyym** [apgapg/search_widget#9]
Hi, it works in the app but I get this exception. Running on newest version 1.0.1, though same error when trying with 1.0.0.

```
I/flutter ( 8648): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY 
I/flutter ( 8648): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter ( 8648): flutter_keyboard_visibility:
I/flutter ( 8648): MissingPluginException(No implementation found for method listen on channel
I/flutter ( 8648): flutter_keyboard_visibility)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.35.0)
[√] Connected device (1 available)

• No issues found!
```

**Comment by apgapg** [comment]
On which device are you running. Using on Platforms other than ios and android will give this exception

**Comment by anthonyym** [comment]
I ran it on my physical Android device plugged in via usb.

**Comment by Joao-b4** [comment]
same problem here.

**Comment by Joao-b4** [comment]
My problem was corrected when completing all required parameters, the error is probably in the usage code.

**Comment by remoteportal** [comment]
What parameters were you missing?  I'm stuck and can't figure this out. 

Shouldn't the compiler complain?

**Comment by remoteportal** [comment]
Seems that the only way to solve this is to clone the repo and remove that dependency.

**Comment by apgapg** [comment]
okay it seems flutter_keyboard_visibility is giving issues.  But if i remove it the keeyboard will not close on focus loose. Thats why i added this

**Comment by apgapg** [comment]
@remoteportal  see this also https://github.com/adee42/flutter_keyboard_visibility/issues/33

**Comment by apgapg** [comment]
fixed on master branch. thanks to @battlecook
